version: '3'

services:

  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - CLUSTERED=true #not being used
      - CLUSTER_WITH=rabbitmq1 #not being used
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    #volumes:
      #- ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    #entrypoint: bash -c ./docker-entrypoint.sh 
    
  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certificate/haproxy.pem:/usr/local/etc/certificate/haproxy.pem:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
    ports:
      - 15672:15672
      - 5672:5672